---
services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    environment:
      ALLOW_SIGNUP: false
      BASE_URL: https://mealie.freedomzero.net
      TZ: Europe/London
    network_mode: service:tailscale
    depends_on: [ tailscale ]
    volumes:
      - mealie-data:/app/data/
    restart: unless-stopped

  tailscale:
    image: ghcr.io/tailscale/tailscale:latest
    container_name: ts-mealie
    hostname: mealie
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_EXTRA_ARGS: '--advertise-tags=tag:container'
      TS_SERVE_CONFIG: /config/tailscale-mealie-funnel.json
      TS_STATE_DIR: /var/lib/tailscale
    volumes:
      - ${PWD}/mealie/state:/var/lib/tailscale
      - ${PWD}/mealie/config:/config
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

volumes:
  mealie-data:
    driver: local
#  ts-mealie:
#    driver: local
