version: 2
jobs:
  build:
    docker:
      - image: hashicorp/packer
    steps:
      - checkout
      - run: 
          name: Packer Version
          command: packer -v

      - run:
          name: Packer bin path
          command: which packer

      - run:
          name: Prep credentials
          command: echo "$GCP_CREDS" | base64 -d > /tmp/credentials.json 

      - run:
          name: Packer run basic
          command: packer build -machine-readable -on-error=cleanup -var-file=packer/common-vars.json packer/base_image.json | tee packer-build.log

      - run:
          name: Get AMI ID
          command: echo "export GMI_ID=$(grep -oE 'packer-citest-\d{10}' packer-build.log)" >> $BASH_ENV  

      - run:
          name: Cleanup
          command: echo "gcloud compute images delete $GMI_ID"
