version: 2
jobs:
  build:
    docker:
      - image: hashicorp/packer
    steps:
      - checkout
      - run: 
          - name: Packer Version
            command: packer -v

          - name: Packer bin path
            command: which packer

          - name: Packer run basic
            command: echo "hello packer"
