version: 2
jobs:
  build:
    docker:
      - image: hashicorp/packer
    steps:
      - checkout
      - run: 
          name: Packer Version
          command: packer -v

      - run:
          name: Packer bin path
          command: which packer

      - run:
          name: Prep credentials
          command: echo "$GCP_CREDS" | base64 --decode > /tmp/credentials.json 

      - run:
          name: Packer run basic
          command: packer build -var-file=packer/common-vars.json packer/base_image.json
