---
- name: Install development essentials.
  package:
    name:
      - git
      - git-filter-repo
      - gitsign
    state: latest

- name: Install other development utilities.
  package:
    name:
      - toolbox
    state: latest

- name: Install virtualisation tools.
  package:
    name:
      - libvirt
      - libvirt-python
      - virt-install
      - virt-manager
      - qemu-base
      - qemu-system-x86
      - virtualbox
      - virtualbox-guest-iso
      - virtualbox-guest-utils
    state: latest

# slirp4ns and fuse-overlayfs are needed for rootless podman
# To set subuid / subgid for user namespaces inside container:
# sudo usermod --add-subuids 100000-165535 \
#              --add-subgids 100000-165535 <username>
- name: Install containerisation tools.
  package:
    name:
      - podman
      - podman-compose
      - buildah
      - skopeo
      - conmon
      - containers-common
      - fuse-overlayfs
      - slirp4netns
    state: latest

- name: Install infrastructure automation tools.
  package:
    name:
      - opentofu
      - terraform
    state: latest

- name: Install terragrunt terraform wrapper
  package:
    name:
      - terragrunt
    state: latest
  tags: [ never, terragrunt ]
