---
# Running:
#
#  ansible-playbook --ask-become-pass --check --tags production --inventory hosts archall.yml
#  ansbile-playbook --inventory hosts --syntax-check archall.yml
#
# Ideally:
#  NixOS should take care of doing package management
#  and configuration for the entire system. But until
#  then, we'll stick to Ansible
#
#  Aspirations:
#  - Immutable / read-only mode for important files ,
#    packages and filesystem
#  - Auto-configure
#  - Safe rollbacks
#
# TODO: Add packages
# - zulucrypt
# - cryptsetup
# - thunderbird-beta-bin (AUR)
# - veracrypt
# - Terraform
# - tfsec-bin
# - terrascan-bin
# - Buildah + Podman
# - Kubernetes?
# 
# TODO: Add services
# - systemd-analyze security <service_name>
#
# TODO: Add IDS
# - AIDS
# - Snort
# - Suricata
#
# TODO: Configure firewall / UFW
# - or nftables
# - ufw
#
# TODO: Fix SSHD config
#   - yay -S czkawka-gui-bin
#   - yay -S libva-utils - for vainfo
#   - yay -S vulkan-intel
#   - yay -S libva-intel-driver
#   - yay -S intel-media-driver
#   - yay -S intel-gpu-tools --> for intel_gpu_top
#
# TODO: System Monitoring Tools
#   - htop
#   - glances
#
# TODO: SHell stuff
# - PS1
# - oh-my-zsh
# - zsh
- hosts: archlaptop
  remote_user: eternaltyro 
  become: yes

  tasks:
    - name: Install password manager
      pacman: name=keepassxc state=latest

    - name: Install backup utility
      pacman: name=borg state=latest

    - name: Install filesystem utilities
      pacman:
        name:
          - f2fs-tools
          - btrfs-progs
          - exfatprogs
          - xfsprogs
        state: latest
      tags: production
          
    - name: Install filesystem utilities via AUR
      pacman:
        name: 
          - ntfs3-dkms
        state: present
        executable: /usr/bin/yay
      tags: never

# slirp4netns and fuse-overlayfs needed for rootless podman
# Do the following to set subuid / subgid for user namespaces inside the container
# sudo usermod --add-subuids 100000-165535 --add-subgids 100000-165535 eternaltyro
#
    - name: Install container stuff incl. rootless podman
      pacman:
        name: 
          - podman
          - conmon
          - containers-common
          - fuse-overlayfs
          - slirp4netns
          - buildah
          - toolbox
        state: present
      tags: production

# TODO:
# - Add ClamAV
# - Add OSSEC
# - Add LMD / Maldet
# - Tripwire
    - name: Install security scanners
      pacman:
        name: 
          - lynis
          - rkhunter
          - arch-audit
          - fail2ban
        state: latest

    - name: Install security scanner dependencies
      pacman:
        name:
          - skdet
          - lsof
          - netstat

    - name: Install security scanners from AUR
      ansible.builtin.command:
        argv:
          - /usr/bin/yay -S
          - tiger
          - chkrootkit
          - google-tsunami-security-scanner
          - openscap
      tags: never

    - name: Install X essentials (legacy)
      pacman:
        name: 
          - xorg-xrdb
          - xorg-xkill
          - xorg-xrandr
          - xorg-server
          - xorg-xinit
          - xf86-input
        state: latest
      tags: never

    - name: Setup Awesome Window Manager and login manager
      pacman:
        name: 
          - awesome
          - slim
          - slim-themes
          - vicious
        state: latest
      tags: never

    - name: Setup terminal multiplexer and shells 
      pacman:
        name: 
          - zsh
          - tmux
          - vim-airline
        state: latest
      tags: shell

    - name: Setup modern audio drivers (pipewire)
      pacman:
        name: 
          - pipewire
          - pipewire-pulse
          - pipewire-media-session
        state: latest

    - name: Setup legacy audio drivers (pulseaudio)
      pacman:
        name:
          - pulseaudio
          - pulseaudio-bluetooth
          - pavucontrol
          - pulseeffects
      tags: never

    - name: Setup Multimedia
      pacman:
        name: 
          - mpd
          - mpc
          - moc
          - vlc
          - alsa-utils
        state: latest
      tags: never

    - name: Setup Office tools
      pacman:
        name: 
          - libreoffice-fresh
          - firefox
          - cherrytree
          - gnucash
        state: latest

    - name: Libreoffice language tools (thesaurus, spell check, hypen rules)
      pacman:
        name:
          - hunspell
          - hunspell-en_us
          - hunspell-en_gb
          - hyphen
          - hyphen-en
          - libmythes
          - mythes-en
          - 

    - name: Install games from flatpak
      community.general.flatpak:
        name:
          - net.pioneerspacesim.Pioneer
          - com.play0ad.zeroad
          - org.wesnoth.Wesnoth
          - com.valvesoftware.Steam
        state: present
      tags: production

    - name: Install office comms apps from flatpak
      community.general.flatpak:
        name:
          - com.slack.Slack
          - com.github.IsmaelMartinez.teams_for_linux
          - com.visualstudio.code
          - us.zoom.Zoom
          - org.gaphor.Gaphor
        state: present
      tags: production

    - name: Install multi-media apps from flatpak
      community.general.flatpak:
        name:
          - com.obsproject.Studio
          - org.blender.Blender
          - org.blender.Blender.Codecs
          - org.gimp.GIMP
          - org.inkscape.Inkscape
        state: present
      tags: production

    - name: Install essential flatpak apps
      community.general.flatpak:
        name:
          - org.keepassxc.KeePassXC
          - org.qbittorrent.qBittorrent
          - com.borgbase.Vorta
          - com.brave.Browser
          - com.github.tchx84.Flatseal
          - im.riot.Riot
          - net.giuspen.cherrytree
          - org.cryptomator.Cryptomator
        state: present
      tags: production

    - name: Install optional flatpak apps
      community.general.flatpak:
        name:
          - org.zotero.Zotero
          - org.telegram.desktop
          - com.github.johnfactotum.Foliate
        state: present
      tags: production

    - name: Install fonts via AUR
      community.general.pacman:
        name:
          - otf-fira-code-mozilla
          - otf-fira-code-symbol
          - otf-openmoji
          - font-mathematica
        state: present
      executable: "/usr/bin/yay"
      tags: onetime

    - name: Install fonts
      pacman:
        name:
          - otf-fira-mono
          - otf-fira-sans
          - ttf-dejavu
          - ttf-bitstream-vera
          - noto-fonts-emoji
          - ttf-liberation
          - ttf-anonymous-pro
          - ttf-inconsolata
          - ttf-linux-libertine
          - ttf-linux-libertine-g
          - adobe-source-code-pro-fonts
          - adobe-source-sans-pro-fonts
          - adobe-source-serif-pro-fonts
          - noto-fonts
          - ttf-roboto
          - awesome-terminal-fonts
          - powerline-fonts
          - tex-gyre-fonts
          - inter-font
          - ttc-iosevka
          - ttf-iosevka-term
          - ttf-iosevka-term-curly
          - ttf-iosevka-term-curly-slab
          - ttf-iosevka-nerd
          - ttc-iosevka-slab
          - ttc-iosevka-curly
          - ttc-iosevka-aile
          - ttf-hack
          - gnu-free-fonts
        state: present
      tags: production

    - name: Install Uncomplicated Firewall (UFW)
      pacman:
        name:
          - ufw

    - name: Configure ufw Firewall Rules
      ufw:
        state: enabled
        policy: allow
        logging: 'on'
#        delete: true

    - name: Rate limit SSH attempts
      ufw:
        comment: Rate limit SSH attempts
        rule: limit
        port: auth
        proto: tcp
        log: true

    - name: Allow RFC1918 networks
      ufw:
        comment: Allow RFC1918 networks
        rule: allow
        src: '{{ item }}'
      loop:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16 

    - name: Allow IPv6 Unique Local Addresses
      ufw:
        rule: allow
        src: fc00::/7
        proto: any
        comment: Allow IPv6 Unique Local Addresses


      
...
