---
# Running:
#
#  ansible-playbook --ask-become-pass --check --tags production --inventory hosts archall.yml
#  ansbile-playbook --inventory hosts --syntax-check archall.yml
#
# Ideally:
#  NixOS should take care of doing package management
#  and configuration for the entire system. But until
#  then, we'll stick to Ansible
#
#  Aspirations:
#  - Immutable / read-only mode for important files ,
#    packages and filesystem
#  - Auto-configure
#  - Safe rollbacks
#
# TODO: Add packages
# - zulucrypt
# - cryptsetup
# - thunderbird-beta-bin (AUR)
# - veracrypt
# - tfsec-bin
# - terrascan-bin
# - Kubernetes?
#
# TODO: Add services
# - systemd-analyze security <service_name>
#
# TODO: Add IDS
# - AIDS
# - Snort
# - Suricata
# - OSSEC
# - LMD / Maldet
# - Tripwire
#
# TODO: ..and security scanners from AUR
# - chkrootkit
# - tiger
# - google-tsunami-security-scanner
# - openscap
#
# TODO: Fix SSHD config
#
# TODO: Install file dedup from AUR
# - czkawka-gui-bin
#
# TODO: System Monitoring Tools
#   - htop
#   - glances
#
# TODO: Shell stuff
# - PS1
# - oh-my-zsh
# - zsh

- name: Install basic applications in Arch.
  hosts: workstation
  become: true

  handlers:

    - name: restart tailscale
      ansible.builtin.service:
        name: tailscaled
        state: restarted

    - name: restart firewall
      ansible.builtin.service:
        name: ufw
        state: restarted

  roles:
    - DevOps-setup
    - clamav
  #  - ldap-integration

  tasks:

    - name: Install core system services.
      ansible.builtin.package:
        name: systemd-resolvconf
        state: present
      tags: production

    - name: Install core fsutils.
      ansible.builtin.package:
        name:
          - btrfs-progs
          - xfsprogs
        state: latest
      tags: production

    - name: Install extra fsutils.
      ansible.builtin.package:
        name:
          - f2fs-tools
          - exfatprogs
        state: present
      tags: never

    - name: Install flatpak runtime.
      ansible.builtin.package:
        name: flatpak
        state: latest
      tags: production

    - name: Add the flathub flatpak repository remote.
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: Add the flathub-beta flatpak repository remote.
      community.general.flatpak_remote:
        name: flathub-beta
        state: present
        flatpakrepo_url: https://dl.flathub.org/beta-repo/flathub-beta.flatpakrepo

    - name: Install security scanners.
      ansible.builtin.package:
        name:
          - fail2ban
          - arch-audit
          - rkhunter
          - lynis
        state: latest
      tags:
        - security
        - production

    - name: Install Netfilter userspace tools.
      ansible.builtin.package:
        name: nftables
        state: latest
      tags: production

    - name: Install Firewall daemon.
      ansible.builtin.package:
        name: firewalld
        state: latest
      tags: [production, never]

    - name: Install firewall frontend.
      ansible.builtin.package:
        name: ufw
        state: latest
      notify: restart firewall
      tags: production

    - name: Install VIM and friends.
      ansible.builtin.package:
        name:
          - vim
          - vim-runtime
        state: latest
      tags: production

    - name: Install system customisations.
      ansible.builtin.package:
        name:
          - zsh
          - tmux
          - vim-airline
          - vim-airline-themes
        state: latest
      tags: production

    - name: Install fwupd utility.
      ansible.builtin.package:
        name: fwupd
        state: latest
      tags: production

    - name: Install Borg backup utility.
      ansible.builtin.package:
        name: borg
        state: latest

    - name: Install essential apps via flatpak.
      become: false
      community.general.flatpak:
        remote: flathub
        name:
          - org.gimp.GIMP
          - org.gnucash.GnuCash
          - org.inkscape.Inkscape
          - org.keepassxc.KeePassXC
          - org.libreoffice.LibreOffice
          - org.openstreetmap.josm
          - org.qownnotes.QOwnNotes
          - org.cryptomator.Cryptomator
          - im.riot.Riot
          - io.mpv.Mpv
          - io.podman_desktop.PodmanDesktop
          - com.borgbase.Vorta
          - com.brave.Browser
          - ch.protonmail.protonmail-bridge
          - com.calibre_ebook.calibre
        state: present

    - name: Install beta apps via flatpak.
      become: false
      community.general.flatpak:
        remote: flathub-beta
        name:
          - org.telegram.desktop
          - org.mozilla.firefox
        state: present
      tags:
        - flatpak
        - flatpak-beta
        - beta

    - name: Install speech dispatcher for Firefox.
      ansible.builtin.package:
        name: speech-dispatcher
        state: latest

    - name: Install optional apps via flatpak.
      become: false
      community.general.flatpak:
        remote: flathub
        name:
          - org.zotero.Zotero
          - in.cinny.Cinny
          - com.github.tchx84.Flatseal
          - com.github.johnfactotum.Foliate
          - org.audacityteam.Audacity
          - network.loki.Session
          - net.giuspen.cherrytree
          - org.blender.Blender
        state: present
      tags:
        - flatpak

    - name: Install games from flatpak.
      become: false
      community.general.flatpak:
        remote: flathub
        name:
          - net.pioneerspacesim.Pioneer
          - com.play0ad.zeroad
          - com.valvesoftware.Steam
        state: present
      tags:
        - flatpak
        - games

    # Flatpak module can't select from multiple available versions.
    - name: Install Battle for Wesnoth from flatpak.
      become: false
      community.general.flatpak:
        remote: flathub
        name:
          - org.wesnoth.Wesnoth
        state: present
      tags:
        - flatpak
        - games
        - never

    - name: Install apps for work from flatpak.
      become: false
      community.general.flatpak:
        remote: flathub
        name:
          - com.slack.Slack
          - us.zoom.Zoom
          - org.gaphor.Gaphor
        state: present
      tags:
        - flatpak
        - work
        - production

    - name: Setup graphics drivers.
      ansible.builtin.package:
        name:
          - libva-utils # --> for vainfo
          - vulkan-intel
          - libva-intel-driver
          - intel-media-driver
          - intel-gpu-tools # --> for intel_gpu_top
        state: latest

    - name: Setup modern audio drivers (pipewire).
      ansible.builtin.package:
        name:
          - pipewire
          - libpipewire
          - pipewire-pulse
          - pipewire-audio
          - pipewire-jack
          - wireplumber
          - libwireplumber
        state: latest

    # moc package deprecated
    - name: Setup Multimedia players.
      ansible.builtin.package:
        name:
          - mpd
          - mpc
          - vlc
        state: latest
      tags: never

    - name: Libreoffice language tools (thesaurus, spell check, hypen rules).
      ansible.builtin.package:
        name:
          - hunspell
          - hunspell-en_us
          - hunspell-en_gb
          - hyphen
          - hyphen-en
          - libmythes
          - mythes-en
        state: present
      tags: never

    # - name: Install fonts via AUR
    #   community.general.pacman:
    #     name:
    #       - otf-fira-code-mozilla
    #       - otf-fira-code-symbol
    #       - otf-openmoji
    #     state: present
    #     executable: "/usr/bin/yay"
    #   tags:
    #     - fonts
    #     - aur

    - name: Install fonts.
      ansible.builtin.package:
        name:
          - otf-fira-mono
          - otf-fira-sans
          - ttf-dejavu
          - ttf-bitstream-vera
          - noto-fonts-emoji
          - ttf-liberation
          - ttf-anonymous-pro
          - ttf-inconsolata
          - ttf-linux-libertine
          - ttf-linux-libertine-g
          - adobe-source-code-pro-fonts
          - adobe-source-sans-pro-fonts
          - adobe-source-serif-pro-fonts
          - noto-fonts
          - ttf-roboto
          - awesome-terminal-fonts
          - powerline-fonts
          - tex-gyre-fonts
          - inter-font
          - ttc-iosevka
          - ttf-iosevka-term
          - ttf-iosevka-nerd
          - ttf-hack
          - gnu-free-fonts
        state: latest
      tags:
        - fonts
        - production

    # deny = ignore
    # reject = inform
    - name: Configure UFW default firewall rules.
      community.general.ufw:
        state: enabled
        policy: reject
        logging: 'on'
        # delete: true
      tags:
        - security
        - firewall

    - name: Rate limit SSH attempts.
      community.general.ufw:
        comment: Rate limit SSH attempts
        rule: limit
        port: ssh
        proto: tcp
        log: true
      notify: restart firewall
      tags:
        - security
        - firewall

    - name: Allow Jellyfin service.
      community.general.ufw:
        comment: Jellyfin access
        rule: allow
        port: '8096'
        proto: tcp
        src: '{{ item }}'
      with_items:
        - 192.168.1.0/24
        - fe80::/64
      notify: restart firewall
      tags:
        - security
        - firewall

    - name: Allow Jellyfin service auto-discovery.
      community.general.ufw:
        comment: Jellyfin service discovery
        rule: allow
        port: '1900'
        proto: udp
        src: '{{ item }}'
      with_items:
        - 192.168.1.0/24
        - fe80::/64
      notify: restart firewall
      tags:
        - security
        - firewall

    - name: Allow Jellyfin service auto-discovery.
      community.general.ufw:
        comment: Jellyfin service discovery
        rule: allow
        port: '7359'
        proto: udp
        src: '{{ item }}'
      with_items:
        - 192.168.1.0/24
        - fe80::/64
      notify: restart firewall
      tags:
        - security
        - firewall

    # Switched to Wayland
    - name: Install X essentials (legacy).
      ansible.builtin.package:
        name:
          - xorg-xrdb
          - xorg-xkill
          - xorg-xrandr
          - xorg-server
          - xorg-xinit
          - xf86-input-libinput
        state: latest
      tags:
        - deprecated
        - never

    # Switched to KDE
    - name: Setup Awesome Window Manager and login manager.
      ansible.builtin.package:
        name:
          - awesome
          - slim
          - slim-themes
          - vicious
        state: latest
      tags:
        - deprecated
        - never
...
