---
# Running:
#
#  ansible-playbook --ask-become-pass --check --tags production --inventory hosts archall.yml
#  ansbile-playbook --inventory hosts --syntax-check archall.yml
#
# Ideally:
#  NixOS should take care of doing package management
#  and configuration for the entire system. But until
#  then, we'll stick to Ansible
#
#  Aspirations:
#  - Immutable / read-only mode for important files ,
#    packages and filesystem
#  - Auto-configure
#  - Safe rollbacks
#
# TODO: Add packages
# - zulucrypt
# - cryptsetup
# - thunderbird-beta-bin (AUR)
# - veracrypt
# - tfsec-bin
# - terrascan-bin
# - Kubernetes?
# 
# TODO: Add services
# - systemd-analyze security <service_name>
#
# TODO: Add IDS
# - AIDS
# - Snort
# - Suricata
# - OSSEC
# - LMD / Maldet
# - Tripwire
#
# TODO: Configure firewall / UFW
# - or nftables
# - ufw
# - firewalld
#
# TODO: Fix SSHD config
#   - yay -S czkawka-gui-bin
#
# TODO: System Monitoring Tools
#   - htop
#   - glances
#
# TODO: Shell stuff
# - PS1
# - oh-my-zsh
# - zsh
- name: Install basic applications in Arch
  hosts: workstation
  become: true

  handlers:

    - name: restart tailscale
      service:
        name: tailscaled
        state: restarted

    - name: restart clamav
      service:
        name: clamav-daemon
        state: restarted

    - name: restart freshclam
      service:
        name: clamav-freshclam
        state: restarted

    - name: restart firewall
      service:
        name: ufw
        state: restarted

  tasks:

    - name: Install core system services
      package:
        name: systemd-resolvconf
        state: present
      tags: production

    - name: Install flatpak
      package:
        name: flatpak
        state: present
      tags: never

    - name: Install security scanners
      package:
        name: clamav
        state: latest
      notify: restart clamav
      tags:
        - security
        - production

    - name: Install security scanners
      package:
        name:
          - fail2ban
          - arch-audit
          - rkhunter
          - lynis
        state: present
      tags:
        - security
        - production

    - name: Install firewall frontend
      package:
        name: ufw
        state: latest
      notify: restart firewall
      tags: production

    # slirp4netns and fuse-overlayfs needed for rootless podman
    # Do the following to set subuid / subgid for user namespaces inside
    # the container:
    # sudo usermod --add-subuids 100000-165535 --add-subgids 100000-165535 eternaltyro
    - name: Install infra dev utilities
      package:
        name:
          - virtualbox
          - opentofu
          - terraform
          - buildah
          - toolbox
          - podman
          - podman-compose
          - conmon
          - containers-common
          - fuse-overlayfs
          - slirp4netns
        state: present

    - name: Install system customisations
      package:
        name:
          - zsh
          - tmux
          - vim-airline
          - borg
        state: present
      tags: never

    - name: Install core fsutils
      package:
        name:
          - btrfs-progs
          - xfsprogs
        state: present
      tags: production

    - name: Install extra fsutils
      package:
        name:
          - f2fs-tools
          - exfatprogs
        state: present
      tags: never

    - name: Install backup utility
      package:
        name: borg
        state: latest

    - name: Install essential apps via flatpak
      become: false
      community.general.flatpak:
        name:
          - org.gimp.GIMP
          - org.gnucash.GnuCash
          - org.inkscape.Inkscape
          - org.keepassxc.KeePassXC
          - org.libreoffice.LibreOffice
          - org.openstreetmap.josm
          - org.qownnotes.QOwnNotes
          - org.cryptomator.Cryptomator
          - im.riot.Riot
          - io.mpv.Mpv
          - io.podman_desktop.PodmanDesktop
          - com.borgbase.Vorta
          - com.brave.Browser
          - ch.protonmail.protonmail-bridge
          - com.calibre_ebook.calibre
        state: present

    - name: Install beta apps via flatpak
      become: false
      community.general.flatpak:
        remote: flathub-beta
        name:
          - org.telegram.desktop
          - org.mozilla.firefox
        state: present
      tags:
        - flatpak
        - flatpak-beta
        - beta

    - name: Install optional apps via flatpak
      become: false
      community.general.flatpak:
        name:
          - org.zotero.Zotero
          - in.cinny.Cinny
          - com.github.tchx84.Flatseal
          - com.github.johnfactotum.Foliate
          - org.audacityteam.Audacity
          - network.loki.Session
          - net.giuspen.cherrytree
          - org.blender.Blender
        state: present
      tags:
        - flatpak

    - name: Install games from flatpak
      become: false
      community.general.flatpak:
        name:
          - net.pioneerspacesim.Pioneer
          - com.play0ad.zeroad
          - org.wesnoth.Wesnoth
          - com.valvesoftware.Steam
        state: present
      tags:
        - flatpak
        - games
        - never

    - name: Install apps for work from flatpak
      become: false
      community.general.flatpak:
        name:
          - com.slack.Slack
          - us.zoom.Zoom
          - org.gaphor.Gaphor
        state: present
      tags:
        - flatpak
        - work
        - production

#    - name: Install chkrootkit and tiger from AUR
#      community.general.pacman:
#        name: 
#          - chkrootkit
#          - tiger
#        state: present
#        executable: "/usr/bin/yay"
#        extra_args: --builddir /var/cache/yay
#      tags:
#        - aur
#        - security
#
#    - name: Install other scanners from AUR
#      community.general.pacman:
#        name: 
#          - google-tsunami-security-scanner
#          - openscap
#        state: latest
#        executable: /usr/bin/yay
#      tags:
#        - aur
#        - security

    - name: Setup graphics drivers
      package:
        name: 
          - libva-utils # --> for vainfo
          - vulkan-intel
          - libva-intel-driver
          - intel-media-driver
          - intel-gpu-tools # --> for intel_gpu_top
        state: latest

    - name: Setup modern audio drivers (pipewire)
      package:
        name: 
          - pipewire
          - libpipewire
          - pipewire-pulse
          - pipewire-audio
          - pipewire-jack
          - wireplumber
          - libwireplumber
        state: latest

    # moc package deprecated
    - name: Setup Multimedia
      package:
        name: 
          - mpd
          - mpc
          - vlc
        state: latest
      tags: never

    - name: Libreoffice language tools (thesaurus, spell check, hypen rules)
      package:
        name:
          - hunspell
          - hunspell-en_us
          - hunspell-en_gb
          - hyphen
          - hyphen-en
          - libmythes
          - mythes-en
        state: present
      tags: never

#    - name: Install fonts via AUR
#      community.general.pacman:
#        name:
#          - otf-fira-code-mozilla
#          - otf-fira-code-symbol
#          - otf-openmoji
#        state: present
#        executable: "/usr/bin/yay"
#      tags: 
#        - fonts
#        - aur
#        - never

    - name: Install fonts
      package:
        name:
          - otf-fira-mono
          - otf-fira-sans
          - ttf-dejavu
          - ttf-bitstream-vera
          - noto-fonts-emoji
          - ttf-liberation
          - ttf-anonymous-pro
          - ttf-inconsolata
          - ttf-linux-libertine
          - ttf-linux-libertine-g
          - adobe-source-code-pro-fonts
          - adobe-source-sans-pro-fonts
          - adobe-source-serif-pro-fonts
          - noto-fonts
          - ttf-roboto
          - awesome-terminal-fonts
          - powerline-fonts
          - tex-gyre-fonts
          - inter-font
          - ttc-iosevka
          - ttf-iosevka-term
          - ttf-iosevka-nerd
          - ttf-hack
          - gnu-free-fonts
        state: latest
      tags:
        - fonts
        - production

    # deny = ignore
    # reject = inform
    - name: Configure ufw Firewall Rules
      community.general.ufw:
        state: enabled
        policy: reject
        logging: 'on'
#        delete: true
      tags:
        - security
        - firewall

    - name: Rate limit SSH attempts
      community.general.ufw:
        comment: Rate limit SSH attempts
        rule: limit
        port: ssh
        proto: tcp
        log: true
      notify: restart firewall
      tags:
        - security
        - firewall

    - name: Allow Jellyfin service
      community.general.ufw:
        comment: Jellyfin access
        rule: allow
        port: '8096'
        proto: tcp
        src: '{{ item }}'
      loop:
        - 192.168.1.0/24
        - fe80::/64
      notify: restart firewall
      tags:
        - security
        - firewall

    - name: Allow Jellyfin service auto-discovery
      community.general.ufw:
        comment: Jellyfin service discovery
        rule: allow
        port: '1900'
        proto: udp
        src: '{{ item }}'
      loop:
        - 192.168.1.0/24
        - fe80::/64
      notify: restart firewall
      tags:
        - security
        - firewall

    - name: Allow Jellyfin service auto-discovery
      community.general.ufw:
        comment: Jellyfin service discovery
        rule: allow
        port: '7359'
        proto: udp
        src: '{{ item }}'
      loop:
        - 192.168.1.0/24
        - fe80::/64
      notify: restart firewall
      tags:
        - security
        - firewall

    # Switched to Wayland
    - name: Install X essentials (legacy)
      package:
        name: 
          - xorg-xrdb
          - xorg-xkill
          - xorg-xrandr
          - xorg-server
          - xorg-xinit
          - xf86-input-libinput
        state: latest
      tags: 
        - deprecated
        - never

    # Switched to KDE
    - name: Setup Awesome Window Manager and login manager
      package:
        name: 
          - awesome
          - slim
          - slim-themes
          - vicious
        state: latest
      tags: 
        - deprecated
        - never
...
